source "https://rubygems.org"

gem 'chromedriver-helper', '~> 1.0.0'
gem 'sauce', '~> 3.5.11'
gem 'sauce-connect', '~> 3.6.2'
gem 'selenium-webdriver', '~> 2.48.1'
gem 'capybara', '~> 2.5.0'
gem 'test-unit', '~> 3.1.3'
gem 'cmdparse', '~> 2.0.6'
gem 'net-ssh', '= 2.9.2'
