source "https://rubygems.org"

gem 'chromedriver-helper', '~> 1.0.0'
gem 'sauce', '~> 3.5.6'
gem 'sauce-connect', '~> 3.6.2'
gem 'selenium-webdriver', '~> 2.47.1'
gem 'capybara', '~> 2.4.4'
gem 'test-unit', '~> 3.1.3'
gem 'cmdparse', '~> 2.0.6'
